name: pinyin-sgns
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - blas=1.0=openblas
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2025.11.4=h06a4308_0
  - expat=2.7.3=h3385a95_0
  - filelock=3.17.0=py39h06a4308_0
  - fsspec=2025.7.0=py39he3bba80_0
  - gmp=6.3.0=h6a678d5_0
  - gmpy2=2.2.1=py39h5eee18b_0
  - importlib-metadata=8.5.0=py39h06a4308_0
  - jinja2=3.1.6=py39h06a4308_0
  - ld_impl_linux-64=2.44=h153f514_2
  - libabseil=20250127.0=cxx17_h6a678d5_0
  - libffi=3.4.4=h6a678d5_1
  - libgcc-ng=11.2.0=h1234567_1
  - libgfortran-ng=11.2.0=h00389a5_1
  - libgfortran5=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libnsl=2.0.0=h5eee18b_0
  - libopenblas=0.3.30=h46f56fc_0
  - libprotobuf=5.29.3=h3cdef7c_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - libtorch=2.6.0=cpu_openblas_h70a2a0d_6
  - libuuid=1.41.5=h5eee18b_0
  - libuv=1.48.0=h5eee18b_0
  - libxcb=1.17.0=h9b100fa_0
  - libzlib=1.3.1=hb25bd0a_0
  - markupsafe=3.0.2=py39h5eee18b_0
  - mpc=1.3.1=h5eee18b_0
  - mpfr=4.2.1=h5eee18b_0
  - mpmath=1.3.0=py39h06a4308_0
  - ncurses=6.5=h7934f7d_0
  - networkx=3.2.1=py39h06a4308_0
  - nomkl=3.0=0
  - openssl=3.0.18=hd6dcaed_0
  - opentelemetry-api=1.37.0=py39h06a4308_0
  - pip=25.2=pyhc872135_1
  - pthread-stubs=0.3=h0ce48e5_1
  - python=3.9.25=h0dcde21_1
  - readline=8.3=hc2a1206_0
  - setuptools=80.9.0=py39h06a4308_0
  - sleef=3.5.1=h5eee18b_2
  - sqlite=3.51.0=h2a70700_0
  - sympy=1.14.0=py39h06a4308_0
  - tk=8.6.15=h54e0aa7_0
  - typing-extensions=4.15.0=py39h06a4308_0
  - typing_extensions=4.15.0=py39h06a4308_0
  - wheel=0.45.1=py39h06a4308_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xz=5.6.4=h5eee18b_1
  - zipp=3.21.0=py39h06a4308_0
  - zlib=1.3.1=hb25bd0a_0
  - pip:
      - accelerate==1.10.1
      - annotated-types==0.7.0
      - blis==0.7.11
      - catalogue==2.0.10
      - certifi==2025.10.5
      - charset-normalizer==3.4.4
      - click==8.1.8
      - cloudpathlib==0.23.0
      - confection==0.1.5
      - cymem==2.0.13
      - gensim==4.4.0
      - hf-xet==1.2.0
      - huggingface-hub==0.36.0
      - idna==3.11
      - jieba==0.42.1
      - joblib==1.5.2
      - langcodes==3.5.1
      - markdown-it-py==3.0.0
      - mdurl==0.1.2
      - murmurhash==1.0.15
      - nltk==3.9.2
      - numpy==1.26.4
      - nvidia-cublas-cu12==12.6.4.1
      - nvidia-cuda-cupti-cu12==12.6.80
      - nvidia-cuda-nvrtc-cu12==12.6.77
      - nvidia-cuda-runtime-cu12==12.6.77
      - nvidia-cudnn-cu12==9.10.2.21
      - nvidia-cufft-cu12==11.3.0.4
      - nvidia-cufile-cu12==1.11.1.6
      - nvidia-curand-cu12==10.3.7.77
      - nvidia-cusolver-cu12==11.7.1.2
      - nvidia-cusparse-cu12==12.5.4.2
      - nvidia-cusparselt-cu12==0.7.1
      - nvidia-nccl-cu12==2.27.3
      - nvidia-nvjitlink-cu12==12.6.85
      - nvidia-nvtx-cu12==12.6.77
      - packaging==25.0
      - pandas==2.3.3
      - pillow==11.3.0
      - preshed==3.0.12
      - psutil==7.1.3
      - pydantic==2.12.5
      - pydantic-core==2.41.5
      - pygments==2.19.2
      - pypinyin==0.55.0
      - python-dateutil==2.9.0.post0
      - pytz==2025.2
      - pyyaml==6.0.3
      - regex==2025.11.3
      - requests==2.32.5
      - rich==14.2.0
      - safetensors==0.6.2
      - scipy==1.13.1
      - shellingham==1.5.4
      - six==1.17.0
      - smart-open==7.4.4
      - spacy==3.8.0
      - spacy-legacy==3.0.12
      - spacy-loggers==1.0.5
      - spacy-pkuseg==1.0.1
      - srsly==2.5.2
      - thinc==8.2.5
      - tokenizers==0.22.1
      - torch==2.8.0+cu126
      - torchaudio==2.8.0+cu126
      - torchvision==0.23.0+cu126
      - tqdm==4.67.1
      - transformers==4.57.1
      - triton==3.4.0
      - typer==0.20.0
      - typer-slim==0.20.0
      - typing-inspection==0.4.2
      - tzdata==2025.2
      - urllib3==2.5.0
      - wasabi==1.1.3
      - weasel==0.4.3
      - wrapt==2.0.1
      - zh-core-web-sm==3.8.0
prefix: /home/jelyn/miniconda3/envs/pinyin-sgns
